# Generated by Django 3.1.7 on 2021-02-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210227_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='test',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
