# Generated by Django 3.1.7 on 2021-02-27 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='test',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
