# Generated by Django 3.1.7 on 2021-03-10 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
