# Generated by Django 3.1.7 on 2021-04-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210311_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='postal_code',
            new_name='post_code',
        ),
    ]
